from typing import Set, Optional
from ..graph import IMGraph

class BaseRISAlgorithm:
    def __init__(self, graph: IMGraph, model: str, random_seed: Optional[int] = None,
                 verbose: bool = False) -> None: ...
    def run(self, k: int, num_rr_sets: int) -> Set[int]: ...
    def get_seeds(self) -> Set[int]: ...
