from typing import Set, TYPE_CHECKING

if TYPE_CHECKING:
    from ..graph import IMGraphCpp

class SusceptibleInfectedRecoveredModel:
    def __init__(self, graph: 'IMGraphCpp', seeds: Set[int], beta: float = 1.0, gamma: float = 0.0, record_activated: bool = False, record_activation_frequency: bool = False) -> None: ...
    
    def set_seeds(self, new_seeds: Set[int]) -> None: ...
    
    def set_beta(self, beta: float) -> None: ...
    
    def set_gamma(self, gamma: float) -> None: ...
    
    def set_record_activated(self, record: bool) -> None: ...
    
    def set_record_activation_frequency(self, record: bool) -> None: ...
    
    def run_single_simulation(self, seed: int | None = None) -> int: ...
    
    def get_activated_nodes(self) -> Set[int]: ...
    
    def get_activation_frequency(self) -> list[int]: ...
    
    def run_monte_carlo_diffusion(self, rounds: int, seed: int | None = None, use_multithread: bool = False, num_threads: int = 0) -> float: ...
